@startuml Class
skinparam {
   defaultfontsize 16
   linetype ortho
}
left to right direction

together {
    class "WindowFactory" as wf {
        create() -> Window
    }
    class "Window" as w {
        - root: tkRoot
        - menu: tkMenu
        - frame: tkFrame
        - time: tkLabel
        - timevar: tkStringVar
        - date: tkLabel
        - datevar: tkStringVar
        - quit_funcs: list[Function]
        + get_time_var() -> tkStringVar
        + get_date_var() -> tkStringVar
        + run()
        + close_window()
        + register_quit_func(Function)
    }
    w <. wf: <<create>>
}

together {
    class "EventFactory" as ef {
        create(Window)
    }
    w <.. ef

    abstract class "EventExecuter" as ee {
        - target: tkWidget
    }
    ef ..> ee: <<create>>

    abstract class "EventConnector" as ec {
        - master: tkMenu
        - executer: EventExecuter
    }
    ef ..> ec: <<create>>
    ec o- ee
}

abstract class "PointManipulator" as pm {
    - target: tkRoot
    - get_geometry() -> Size, Point
    + get_point() -> Point
    + set_point(int, int)
}

together {
    class "WindowCloser" as wcr {
        - target: tkRoot
        + close()
    }
    ee <|.. wcr

    class "WindowCloseEvent" as wcre {
        - master: tkMenu
        - closer: WindowCloser
        + event()
    }
    ec <|.. wcre
}

together {
    class "TopmostSwitcher" as tms {
        - target: tkRoot
        + is_topmost() -> bool
        + keep()
        + release()
    }
    ee <|.. tms

    class "TopmostSwitchEvent" as tmse {
        - master: tkMenu
        - swicher: TopmostSwitcher
        - select_msg() -> str
        + event()
    }
    ec <|.. tmse
}

together {
    abstract class "WatchObserver" as wo {
        - target: tkStringVar
        - last_time: datetime
        + update(datetime)
    }
    ee <|-- wo

    class "TimeObserver" as to {
        + update(datetime)
    }
    wo <|.. to

    class "DateObserver" as do {
        + update(datetime)
    }
    wo <|.. do

    abstract class "WatchCounter" as wc {
        - observers: list[WatchObsever]
        + add_observer(WatchObserver)
        # notify_observer(datetime)
        # {abstract} count()
        + quit()
    }

    class "TimeCounter" as tc {
        - count()
    }
    wc <|.. tc
    wo "2..n" -l-o wc
}
@enduml
