name: release
run-name: OLW release
on:
  push:
    branches:
      - TAKE4548/issue20
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          pythons-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install poetry
          poetry config --list
          poetry install

      - name: Lint with flake8
        run: poetry run flake8 ./src --count
        continue-on-error: true

      - name: Tests with pytest
        run: poetry run pytest
        env:
          DISPLAY: ":0"
        continue-on-error: true

      - name: Build with poetry
        run: poetry build